def stopword(item):
    item = item.replace("포항," , "")
    item = item.replace("포항시," , "")
    item = item.replace("남구," , "")
    item = item.replace("북구," , "")
    item = item.replace("경북," , "")
    item = item.replace("경상북도," , "")
    item = item.replace("상주," , "")
    item = item.replace("상주시," , "")
    item = item.replace("태백," , "")
    item = item.replace("태백시," , "")
    item = item.replace("강원," , "")
    item = item.replace("강원도," , "")
    item = item.replace("광명," , "")
    item = item.replace("광명시," , "")
    item = item.replace("경기," , "")
    item = item.replace("경기도," , "")
    item = item.replace("목포," , "")
    item = item.replace("목포시," , "")
    item = item.replace("전남," , "")
    item = item.replace("전라남도," , "")
    item = item.replace("통영," , "")
    item = item.replace("통영시," , "")
    item = item.replace("경남," , "")
    item = item.replace("경상남도," , "")
    
    return item